# Generated by Django 2.0.2 on 2018-09-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180930_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefile',
            new_name='image',
        ),
    ]
